module.exports = [
    {
        "in":"/1194/",
        "out":"/blog"
    },
    {
        "in":"/2011/12/",
        "out":"/blog"
    },
    {
        "in":"/2012/03/",
        "out":"/blog"
    },
    {
        "in":"/2012/06/",
        "out":"/blog"
    },
    {
        "in":"/2013/02/",
        "out":"/blog"
    },
    {
        "in":"/2013/05/",
        "out":"/blog"
    },
    {
        "in":"/2013/06/",
        "out":"/blog"
    },
    {
        "in":"/2014/04/",
        "out":"/blog"
    },
    {
        "in":"/2014/12/",
        "out":"/blog"
    },
    {
        "in":"/2015/01/",
        "out":"/blog"
    },
    {
        "in":"/2015/02/",
        "out":"/blog"
    },
    {
        "in":"/2015/03/",
        "out":"/blog"
    },
    {
        "in":"/2015/04/",
        "out":"/blog"
    },
    {
        "in":"/2015/05/",
        "out":"/blog"
    },
    {
        "in":"/2015/06/",
        "out":"/blog"
    },
    {
        "in":"/2015/08/",
        "out":"/blog"
    },
    {
        "in":"/2015/09/",
        "out":"/blog"
    },
    {
        "in":"/2015/10/",
        "out":"/blog"
    },
    {
        "in":"/2015/11/",
        "out":"/blog"
    },
    {
        "in":"/2015/12/",
        "out":"/blog"
    },
    {
        "in":"/2016/01/",
        "out":"/blog"
    },
    {
        "in":"/2016/03/",
        "out":"/blog"
    },
    {
        "in":"/2016/04/",
        "out":"/blog"
    },
    {
        "in":"/2016/05/",
        "out":"/blog"
    },
    {
        "in":"/2016/09/",
        "out":"/blog"
    },
    {
        "in":"/2016/10/",
        "out":"/blog"
    },
    {
        "in":"/2016/11/",
        "out":"/blog"
    },
    {
        "in":"/2016/12/",
        "out":"/blog"
    },
    {
        "in":"/2017/01/",
        "out":"/blog"
    },
    {
        "in":"/2017/06/",
        "out":"/blog"
    },
    {
        "in":"/2017/07/",
        "out":"/blog"
    },
    {
        "in":"/2018/10/",
        "out":"/blog"
    },
    {
        "in":"/2018/11/",
        "out":"/blog"
    },
    {
        "in":"/2019/02/",
        "out":"/blog"
    },
    {
        "in":"/2019/03/",
        "out":"/blog"
    },
    {
        "in":"/2019/05/",
        "out":"/blog"
    },
    {
        "in":"/2019/07/",
        "out":"/blog"
    },
    {
        "in":"/2019/08/",
        "out":"/blog"
    },
    {
        "in":"/2019/10/",
        "out":"/blog"
    },
    {
        "in":"/2019/12/",
        "out":"/blog"
    },
    {
        "in":"/2020/01/",
        "out":"/blog"
    },
    {
        "in":"/2020/02/",
        "out":"/blog"
    },
    {
        "in":"/2020/03/",
        "out":"/blog"
    },
    {
        "in":"/2020/06/",
        "out":"/blog"
    },
    {
        "in":"/2020/07/",
        "out":"/blog"
    },
    {
        "in":"/29er-le-skiff-des-equipages-legers/",
        "out":"/bateaux/29er"
    },
    {
        "in":"/346/",
        "out":"/"
    },
    {
        "in":"/410/",
        "out":"/"
    },
    {
        "in":"/420-lanaverre/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-lenam-bleu-clair/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-nautivela-doccasion-a-vendre/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-roga-bleu-ciel/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-rondar-doccasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-rondar/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-ziegelmeyer-equipe-regate-2/",
        "out":"/bateaux/420"
    },
    {
        "in":"/420-ziegelmeyer-equipe-regate/",
        "out":"/bateaux/420"
    },
    {
        "in":"/470-devoti-excellent-etat-equipe-regate/",
        "out":"/bateaux/470"
    },
    {
        "in":"/505-parker/",
        "out":"/bateaux/505"
    },
    {
        "in":"/929/",
        "out":"/"
    },
    {
        "in":"/a-lassaut-de-cezembre/",
        "out":"/"
    },
    {
        "in":"/anne-en-rs600/",
        "out":"/"
    },
    {
        "in":"/author/admin/",
        "out":"/"
    },
    {
        "in":"/belle-navigation-dhiver/",
        "out":"/"
    },
    {
        "in":"/blog/materiel-neuf/accastillage",
        "out":"/blog"
    },
    {
        "in":"/blog/materiel-neuf/accastillage/",
        "out":"/blog"
    },
    {
        "in":"/blog/materiel-neuf/les-tauds/",
        "out":"/blog"
    },
    {
        "in":"/blog/materiel-neuf/remorque-mise-a-leau/",
        "out":"/blog"
    },
    {
        "in":"/blog/materiel-neuf/remorques/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/entretien-hivernage/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/greement-accastillage/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/le-polyester/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/le-vernis/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/notre-savoir-faire/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/revisions/",
        "out":"/blog"
    },
    {
        "in":"/blog/services/voilerie/",
        "out":"/blog"
    },
    {
        "in":"/boss-et-solo-font-bon-menage/",
        "out":"/bateaux/boss"
    },
    {
        "in":"/breizhskiff-a-granville/",
        "out":"/blog"
    },
    {
        "in":"/buzz-doccasion-a-vendre-tres-recent/",
        "out":"/bateaux/buzz"
    },
    {
        "in":"/calendrier-2016-emeraude-initiative-deriveurs/",
        "out":"/blog"
    },
    {
        "in":"/cap-sud-presque-neuf/",
        "out":"/bateaux/cap-sud"
    },
    {
        "in":"/caravelle-recherche-balades-en-famille/",
        "out":"/bateaux/caravelle"
    },
    {
        "in":"/contender-coque-polyester-pont-bois-vernis/",
        "out":"/bateaux/contender"
    },
    {
        "in":"/contender-doccasion-a-vendre-2/",
        "out":"/bateaux/contender"
    },
    {
        "in":"/contender-doccasion-a-vendre/",
        "out":"/bateaux/contender"
    },
    {
        "in":"/contender-pont-bois/",
        "out":"/bateaux/contender"
    },
    {
        "in":"/contender/",
        "out":"/bateaux/contender"
    },
    {
        "in":"/cornish-cove/",
        "out":"/bateaux/cornish-cove"
    },
    {
        "in":"/deriveur-420-boutemy-occasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-fountaine-pajot-occasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-occasion-lanaverre/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-rondar-nouvelle-jauge-occasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-rondar-occasion-2/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-rondar-occasion-3/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-rondar-occasion-4/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-rondar-occasion-5/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-rondar-occasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-yachting-france-occasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-420-zyegelmayer-occasion/",
        "out":"/bateaux/420"
    },
    {
        "in":"/deriveur-470-mackay-doccasion/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-mackay-occasion/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-nautivella-occasion-2/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-nautivella-occasion/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-parker-occasion-2/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-parker-occasion/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-yachting-france-occasion/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-470-zyegelmayer-occasion/",
        "out":"/bateaux/470"
    },
    {
        "in":"/deriveur-485-occasion/",
        "out":"/bateaux/505"
    },
    {
        "in":"/deriveur-505-occasion/",
        "out":"/bateaux/505"
    },
    {
        "in":"/deriveur-505-rondar-occasion/",
        "out":"/bateaux/505"
    },
    {
        "in":"/deriveur-buzz-topper-occasion/",
        "out":"/bateaux/buzz"
    },
    {
        "in":"/deriveur-byte-occasion/",
        "out":"/bateaux/byte"
    },
    {
        "in":"/deriveur-caravelle-occasion/",
        "out":"/bateaux/caravelle"
    },
    {
        "in":"/deriveur-construction-amateur-occasion/",
        "out":"/blog"
    },
    {
        "in":"/deriveur-contender-doccasion/",
        "out":"/bateaux/contender"
    },
    {
        "in":"/deriveur-enterprise-doccasion-2/",
        "out":"/bateaux/enterprise"
    },
    {
        "in":"/deriveur-enterprise-doccasion-3/",
        "out":"/bateaux/enterprise"
    },
    {
        "in":"/deriveur-enterprise-doccasion/",
        "out":"/bateaux/enterprise"
    },
    {
        "in":"/deriveur-enterprise-occasion-2/",
        "out":"/bateaux/enterprise"
    },
    {
        "in":"/deriveur-enterprise-occasion/",
        "out":"/bateaux/enterprise"
    },
    {
        "in":"/deriveur-equipe-doccasion/",
        "out":"/bateaux/equipe"
    },
    {
        "in":"/deriveur-fireball-doccasion/",
        "out":"/bateaux/fireball"
    },
    {
        "in":"/deriveur-firefly-occasion/",
        "out":"/bateaux/firefly"
    },
    {
        "in":"/deriveur-fun-power-doccasion/",
        "out":"/bateaux/fun-power"
    },
    {
        "in":"/deriveur-gp14-doccasion-2/",
        "out":"/bateaux/gp-14"
    },
    {
        "in":"/deriveur-gp14-doccasion/",
        "out":"/bateaux/gp-14"
    },
    {
        "in":"/deriveur-iso-doccasion/",
        "out":"/bateaux/iso"
    },
    {
        "in":"/deriveur-jy15-doccasion/",
        "out":"/bateaux"
    },
    {
        "in":"/deriveur-laser-13-doccasion/",
        "out":"/bateaux/laser-13"
    },
    {
        "in":"/deriveur-laser-13-occasion/",
        "out":"/bateaux/laser-13"
    },
    {
        "in":"/deriveur-laser-16-occasion/",
        "out":"/bateaux/laser-16"
    },
    {
        "in":"/deriveur-laser-2000-occasion/",
        "out":"/bateaux/laser-2000"
    },
    {
        "in":"/deriveur-laser-3000-occasion/",
        "out":"/bateaux/laser-3000"
    },
    {
        "in":"/deriveur-laser-bug-occasion/",
        "out":"/bateaux/laser-bug"
    },
    {
        "in":"/deriveur-laser-ii-regatta-doccasion/",
        "out":"/bateaux/laser-2"
    },
    {
        "in":"/deriveur-laser-standard-doccasion/",
        "out":"/bateaux/laser-standard"
    },
    {
        "in":"/deriveur-merlin-rocket-occasion/",
        "out":"/bateaux/merlin-rocket"
    },
    {
        "in":"/deriveur-mirror-occasion/",
        "out":"/bateaux/mirror"
    },
    {
        "in":"/deriveur-moth-europe-doccasion-2/",
        "out":"/bateaux/moth-europe"
    },
    {
        "in":"/deriveur-moth-europe-doccasion/",
        "out":"/bateaux/moth-europe"
    },
    {
        "in":"/deriveur-newstar-occasion/",
        "out":"/bateaux/"
    },
    {
        "in":"/deriveur-phileas-3-60/",
        "out":"/bateaux/phileas-360"
    },
    {
        "in":"/deriveur-plan-fife-12-pieds-occasion/",
        "out":"/bateaux/"
    },
    {
        "in":"/deriveur-ponant-deschamps-occasion/",
        "out":"/bateaux/ponant"
    },
    {
        "in":"/deriveur-rs-200-ldc-occasion/",
        "out":"/bateaux/rs-200"
    },
    {
        "in":"/deriveur-rs-400-ldc-occasion/",
        "out":"/bateaux/rs-400"
    },
    {
        "in":"/deriveur-rs-500/",
        "out":"/bateaux/rs-500"
    },
    {
        "in":"/deriveur-rs-600-doccasion/",
        "out":"/bateaux/rs-600"
    },
    {
        "in":"/deriveur-services-au-grand-prix-de-lecole-navale/",
        "out":"/blog"
    },
    {
        "in":"/deriveur-solo-doccasion-2/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/deriveur-solo-doccasion-3/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/deriveur-solo-doccasion-4/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/deriveur-solo-doccasion/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/deriveur-solo-occasion-2/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/deriveur-solo-occasion/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/deriveur-tideway-12-doccasion/",
        "out":"/bateaux/"
    },
    {
        "in":"/deriveur-topaz-vibe/",
        "out":"/bateaux/"
    },
    {
        "in":"/deriveur-vaurien-occasion/",
        "out":"/bateaux/vaurien"
    },
    {
        "in":"/deriveur-wayfarer-doccasion/",
        "out":"/bateaux/wayfarer"
    },
    {
        "in":"/deriveur-zef-la-prairie-occasion/",
        "out":"/bateaux/zef"
    },
    {
        "in":"/deriveurs-buzz-occasions-topper/",
        "out":"/bateaux/buzz"
    },
    {
        "in":"/entrainement-dhiver-en-rance/",
        "out":"/blog"
    },
    {
        "in":"/entrainement-skiff-du-13-mars-2016-a-st-suliac/",
        "out":"/blog"
    },
    {
        "in":"/europe-cherche-barreur-se/",
        "out":"/bateaux/moth-europe"
    },
    {
        "in":"/europe-doccasion/",
        "out":"/bateaux/moth-europe"
    },
    {
        "in":"",
        "out":"/blog"
    },
    {
        "in":"/fermetures-exceptionnelles/",
        "out":"/blog"
    },
    {
        "in":"/gp-crouesty-2014/",
        "out":"/blog"
    },
    {
        "in":"/hobie-cat-15-un-catamaran-pour-toute-la-famille/",
        "out":"/bateaux/bateaux"
    },
    {
        "in":"/hobie-cat-16-easy-doccasion-a-vendre/",
        "out":"/bateaux/bateaux"
    },
    {
        "in":"/iso-doccasion-a-vendre/",
        "out":"/bateaux/iso"
    },
    {
        "in":"/kl-cat-15-un-catamaran-sur-et-ludique/",
        "out":"/bateaux"
    },
    {
        "in":"/la-newsletter-deid-%e2%9b%b5/",
        "out":"/blog"
    },
    {
        "in":"/lanaverre-320-doccasion-a-vendre/",
        "out":"/bateaux/lanaverre-320"
    },
    {
        "in":"/lancement-du-m750-au-nautic/",
        "out":"/blog"
    },
    {
        "in":"/laser-16-doccasion-a-vendre/",
        "out":"/bateaux/laser-16"
    },
    {
        "in":"/laser-3000-doccasion/",
        "out":"/bateaux/laser-3000"
    },
    {
        "in":"/laser-4000/",
        "out":"/bateaux/laser-4000"
    },
    {
        "in":"/laser-beige-doccasion/",
        "out":"/bateaux/laser-standard"
    },
    {
        "in":"/laser-doccasion-a-vendre/",
        "out":"/bateaux/laser-standard"
    },
    {
        "in":"/laser-ii-regatta-tout-en-finesse-et-legerete/",
        "out":"/bateaux/laser-2"
    },
    {
        "in":"/laser-ii-regatta-un-double-leger-et-plein-de-sensations/",
        "out":"/bateaux/laser-2"
    },
    {
        "in":"/laser-jaune-doccasion/",
        "out":"/bateaux/laser-standard"
    },
    {
        "in":"/laser-jaune-excellent-etat/",
        "out":"/bateaux/laser-standard"
    },
    {
        "in":"/laser-vortex-doccasion-a-vendre/",
        "out":"/bateaux/laser-vortex"
    },
    {
        "in":"/le-chantier-est-en-fleur/",
        "out":"/blog"
    },
    {
        "in":"/le-solo-a-la-fete-du-naustisme/",
        "out":"/blog"
    },
    {
        "in":"/liens/",
        "out":"/blog"
    },
    {
        "in":"/ma-premiere-nav-en-rs600/",
        "out":"/blog"
    },
    {
        "in":"/magnifique-doris-doccasion/",
        "out":"/blog"
    },
    {
        "in":"/materiel-deurope-presque-neuf-mat-voile-lame-de-safran-derive/",
        "out":"/blog"
    },
    {
        "in":"/materiel-neuf/",
        "out":"/blog"
    },
    {
        "in":"/materiel-neuf/accastillage/",
        "out":"/blog"
    },
    {
        "in":"/materiel-neuf/les-tauds/",
        "out":"/blog"
    },
    {
        "in":"/materiel-neuf/remorque-mise-a-leau/",
        "out":"/blog"
    },
    {
        "in":"/materiel-neuf/remorques/",
        "out":"/blog"
    },
    {
        "in":"/mise-a-leau-deriveur-grosse-roue/",
        "out":"/blog"
    },
    {
        "in":"/mise-a-leau-pliable-doccasion-petit-deriveur/",
        "out":"/blog"
    },
    {
        "in":"/navigation-carnac-25-mai-2015/",
        "out":"/blog"
    },
    {
        "in":"/navigation-dans-le-fremur-dimanche-10-avril-2016/",
        "out":"/blog"
    },
    {
        "in":"/navigation-de-noel-en-deriveurs-solo/",
        "out":"/blog"
    },
    {
        "in":"/navigation-dhiver-en-29erxx/",
        "out":"/blog"
    },
    {
        "in":"/navigation-du-4-decembre-a-la-plage-du-prieure/",
        "out":"/blog"
    },
    {
        "in":"/navigation-du-dimanche-21-juin-a-st-suliac/",
        "out":"/blog"
    },
    {
        "in":"/navigation-du-lundi-de-paques-le-06-avril-2015/",
        "out":"/blog"
    },
    {
        "in":"/navigation-eid-5-avril-2015/",
        "out":"/blog"
    },
    {
        "in":"/navigation-en-bretagne-sud-arradon-et-carnac/",
        "out":"/blog"
    },
    {
        "in":"/navigation-entrainement-du-29-septembre-2015-en-skiff/",
        "out":"/blog"
    },
    {
        "in":"/navigation-hivernale-en-rance/",
        "out":"/blog"
    },
    {
        "in":"/navigation/",
        "out":"/blog"
    },
    {
        "in":"/naviguer-toujours-naviguer/",
        "out":"/blog"
    },
    {
        "in":"/nos-occasions/",
        "out":"/blog"
    },
    {
        "in":"/nous-trouver/",
        "out":"/blog"
    },
    {
        "in":"/nouveaux-horaires-douverture/",
        "out":"/blog"
    },
    {
        "in":"/optimist-bois-doccasion/",
        "out":"/blog"
    },
    {
        "in":"/petit-mauraudeur-cherche-a-caboter/",
        "out":"/blog"
    },
    {
        "in":"/premiere-navigation-de-sing-sing-le-30032014-a-saint-suliac/",
        "out":"/blog"
    },
    {
        "in":"/premiere-sortie-au-trapeze/",
        "out":"/blog"
    },
    {
        "in":"/premiere-sortie-en-boss/",
        "out":"/blog"
    },
    {
        "in":"/prindle-19-un-catamaran-pour-voler/",
        "out":"/bateaux"
    },
    {
        "in":"/projet-initiative-deriveurs/",
        "out":"/blog"
    },
    {
        "in":"/quillard-de-sport-flying-fifteen-occasion/",
        "out":"/blog"
    },
    {
        "in":"/rassemblement-de-deriveurs-sur-la-rance/",
        "out":"/blog"
    },
    {
        "in":"/re-collage-dun-mat-de-yole-ok/",
        "out":"/blog"
    },
    {
        "in":"/recit-de-la-navigation-du-dimanche-31-mai-2015/",
        "out":"/blog"
    },
    {
        "in":"/recollage-listons-dun-merlin-rocket/",
        "out":"/blog"
    },
    {
        "in":"/recyclage-de-votre-470/",
        "out":"/blog"
    },
    {
        "in":"/regate-breizhskiff-a-sanguinet/",
        "out":"/blog"
    },
    {
        "in":"/regate-departementale-interserie-a-baden/",
        "out":"/blog"
    },
    {
        "in":"/regate-departementale-st-suliac/",
        "out":"/blog"
    },
    {
        "in":"/regate-des-zebres/",
        "out":"/blog"
    },
    {
        "in":"/regate-interserie-a-quiberon/",
        "out":"/blog"
    },
    {
        "in":"/regate-tavl-a-tregastel-le-18-avril/",
        "out":"/blog"
    },
    {
        "in":"/regate-tavl-trebeurden/",
        "out":"/blog"
    },
    {
        "in":"/remontee-de-la-rance-en-byte-cii/",
        "out":"/blog"
    },
    {
        "in":"/remorque-combinee-laser-neuve/",
        "out":"/blog"
    },
    {
        "in":"/remorque-double-de-route-montee-sans-effort/",
        "out":"/blog"
    },
    {
        "in":"/reparation-barrot-et-tableau-arriere-470-parker/",
        "out":"/blog"
    },
    {
        "in":"/reparation-du-barrot-sur-un-deriveur-470-roga/",
        "out":"/blog"
    },
    {
        "in":"/reparation-pont-arriere-ic10/",
        "out":"/blog"
    },
    {
        "in":"/repontage-dune-yole-ok/",
        "out":"/blog"
    },
    {
        "in":"/restauration-vernis-coque-moth-europe/",
        "out":"/blog"
    },
    {
        "in":"/restauration-vernis-sur-une-superbe-yole-ok-barat/",
        "out":"/blog"
    },
    {
        "in":"/rs-200-doccasion-a-vendre/",
        "out":"/bateaux/rs-200"
    },
    {
        "in":"/rs-vareo/",
        "out":"/bateaux/rs-vision"
    },
    {
        "in":"/rs-vision-doccasion-a-vendre/",
        "out":"/bateaux/rs-vision"
    },
    {
        "in":"/rs200-doccasion-a-vendre/",
        "out":"/bateaux/rs-200"
    },
    {
        "in":"/rs400-doccasion/",
        "out":"/bateaux/rs-400"
    },
    {
        "in":"/rs600-un-skiff-pour-apprendre/",
        "out":"/bateaux/rs-600"
    },
    {
        "in":"/rs800-skiff-double-trapeze/",
        "out":"/bateaux/rs-800"
    },
    {
        "in":"/saint-suliac-21-12-2014/",
        "out":"/blog"
    },
    {
        "in":"/scoop-deriveur-services-de-retour-sur-le-web/",
        "out":"/blog"
    },
    {
        "in":"/services-bis/",
        "out":"/services"
    },
    {
        "in":"/services/",
        "out":"/services"
    },
    {
        "in":"/services/entretien-hivernage/",
        "out":"/services"
    },
    {
        "in":"/services/greement-accastillage/",
        "out":"/services"
    },
    {
        "in":"/services/le-polyester/",
        "out":"/services"
    },
    {
        "in":"/services/le-vernis/",
        "out":"/services"
    },
    {
        "in":"/services/notre-savoir-faire/",
        "out":"/services"
    },
    {
        "in":"/services/revisions/",
        "out":"/services"
    },
    {
        "in":"/sing-sing-skiff-premiere-mise-a-leau-version-longue/",
        "out":"/blog"
    },
    {
        "in":"/skiff-double-trapeze-topper-boss/",
        "out":"/blog"
    },
    {
        "in":"/solo-composite-coque-amande-pont-bois-vernis/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/solo-en-fibre-a-mettre-entre-toutes-les-mains/",
        "out":"/bateaux/solo"
    },
    {
        "in":"/speed-feet-18-doccasion-a-vendre/",
        "out":"/bateaux/finn"
    },
    {
        "in":"/splendide-finn-une-occasion-a-ne-pas-rater/",
        "out":"/bateaux/finn"
    },
    {
        "in":"/splendide-yole-ok/",
        "out":"/blog"
    },
    {
        "in":"/type/image/",
        "out":"/blog"
    },
    {
        "in":"/type/video/",
        "out":"/blog"
    },
    {
        "in":"/un-solo-dessale-a-deriveur-service/",
        "out":"/blog"
    },
    {
        "in":"/vaurien-voile-aviron-un-classique-revisite/",
        "out":"/blog"
    },
    {
        "in":"/voile-aviron-bounty-doccasion/",
        "out":"/blog"
    },
    {
        "in":"/voile-aviron-drascombe-scaffie/",
        "out":"/blog"
    },
    {
        "in":"/voile-laser-a-corne/",
        "out":"/blog"
    },
    {
        "in":"/voilerie/",
        "out":"/services"
    },
    {
        "in":"/voiles-decors-realise-un-jeu-de-voiles-neuf-pour-le-class-j-ranger/",
        "out":"/services"
    },
    {
        "in":"/wombat-exemplaire-unique/",
        "out":"/blog"
    },
    {
        "in":"/yachting-world-day-boat-doccasion/",
        "out":"/blog"
    },
    {
        "in":"/yachting-world-day-boat/",
        "out":"/blog"
    }      
]